image: docker:20.10.16

stages:
  - docker

variables:
  IMAGE_NAME: simonettifr/demo-app
  IMAGE_TAG: springboot-app-1.0
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

build_image:
  stage: docker
  services:
    - docker:20.10.16-dind
  before_script:
    - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
