stages:
  - build

backend_build:
  image: maven:3.9-eclipse-temurin-17
  stage: build
  script:
    - cd backend
    - mvn clean install

frontend_build:
  image: node:20
  stage: build
  script:
    - cd frontend
    - npm ci
    - npm run test
    - npm run build
