stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Installiere Abhängigkeiten..."
    - echo "Baue Anwendung..."

test-job:
  stage: test
  script:
    - echo "Führe Unit-Tests aus..."
