on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME_BACKEND: simonettifr/backend
  IMAGE_NAME_FRONTEND: simonettifr/frontend

jobs:
  docker_backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: |
          docker build -t $IMAGE_NAME_BACKEND:latest ./backend
          docker push $IMAGE_NAME_BACKEND:latest

  docker_frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: |
          docker build -t $IMAGE_NAME_FRONTEND:latest ./frontend
          docker push $IMAGE_NAME_FRONTEND:latest
