name: CI Workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        run: echo "Hello World"
  jobnumber2:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: sdfsdfsdf
        run: echo "Bubale Bub"
  
