name: CI Workflow

on:
  push:
    branches:
      - master

jobs:
  show-backendapplication:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Datei anzeigen
        run: cat backend/src/main/java/org/example/backend/BackendApplication.java
